# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{usps}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Gaffney"]
  s.date = %q{2010-02-05}
  s.description = %q{USPS Webtools API for Ruby.}
  s.email = %q{gaffneyc@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/usps.rb",
     "lib/usps/address.rb",
     "lib/usps/client.rb",
     "lib/usps/configuration.rb",
     "lib/usps/errors.rb",
     "lib/usps/request.rb",
     "lib/usps/request/address_standardization.rb",
     "lib/usps/request/base.rb",
     "lib/usps/request/city_and_state_lookup.rb",
     "lib/usps/request/delivery_confirmation.rb",
     "lib/usps/request/delivery_confirmation_certify.rb",
     "lib/usps/request/tracking_lookup.rb",
     "lib/usps/request/zip_code_lookup.rb",
     "lib/usps/response.rb",
     "lib/usps/response/address_standardization.rb",
     "lib/usps/response/base.rb",
     "lib/usps/response/city_and_state_lookup.rb",
     "lib/usps/response/delivery_confirmation.rb",
     "lib/usps/response/tracking_lookup.rb",
     "lib/usps/test.rb",
     "lib/usps/test/address_verification.rb",
     "lib/usps/test/city_and_state_lookup.rb",
     "lib/usps/test/delivery_confirmation.rb",
     "lib/usps/test/tracking_lookup.rb",
     "lib/usps/test/zip_code_lookup.rb",
     "spec/address_spec.rb",
     "spec/configuration_spec.rb",
     "spec/data/address_standardization_1.xml",
     "spec/data/address_standardization_2.xml",
     "spec/data/city_and_state_lookup_1.xml",
     "spec/data/city_and_state_lookup_2.xml",
     "spec/data/delivery_confirmation_1.xml",
     "spec/data/delivery_confirmation_2.xml",
     "spec/data/tracking_lookup_1.xml",
     "spec/data/tracking_lookup_2.xml",
     "spec/request/address_standardization_spec.rb",
     "spec/request/base_spec.rb",
     "spec/request/city_and_state_lookup_spec.rb",
     "spec/request/delivery_confirmation_certify_spec.rb",
     "spec/request/delivery_confirmation_spec.rb",
     "spec/request/tracking_spec.rb",
     "spec/request/zip_code_lookup_spec.rb",
     "spec/response/address_standardization_spec.rb",
     "spec/response/base_spec.rb",
     "spec/response/city_and_state_lookup_spec.rb",
     "spec/response/delivery_confirmation_spec.rb",
     "spec/response/tracking_lookup_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/usps_spec.rb",
     "usps.gemspec"
  ]
  s.homepage = %q{http://github.com/gaffneyc/usps}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{USPS Webtools API for Ruby}
  s.test_files = [
    "spec/address_spec.rb",
     "spec/configuration_spec.rb",
     "spec/request/address_standardization_spec.rb",
     "spec/request/base_spec.rb",
     "spec/request/city_and_state_lookup_spec.rb",
     "spec/request/delivery_confirmation_certify_spec.rb",
     "spec/request/delivery_confirmation_spec.rb",
     "spec/request/signature_confirmation_spec.rb",
     "spec/request/tracking_spec.rb",
     "spec/request/zip_code_lookup_spec.rb",
     "spec/response/address_standardization_spec.rb",
     "spec/response/base_spec.rb",
     "spec/response/city_and_state_lookup_spec.rb",
     "spec/response/delivery_confirmation_spec.rb",
     "spec/response/signature_confirmation_spec.rb",
     "spec/response/tracking_lookup_spec.rb",
     "spec/spec_helper.rb",
     "spec/usps_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, [">= 2.1.2"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_runtime_dependency(%q<typhoeus>, [">= 0.1.18"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<builder>, [">= 2.1.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_dependency(%q<typhoeus>, [">= 0.1.18"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 2.1.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
    s.add_dependency(%q<typhoeus>, [">= 0.1.18"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

